print('What do you get when you cross a snowman and a vampire?')
input()
print('Frostbite!')
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock Knock.')
input()
print('Who\'s there?')
input()
print('Interrupting cow.')
input()
print('Interrupting wh', end='')
print('-MOO!')

